name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  SERVICE_PATH: /home/od/moimism
  JAR_NAME: od-cloud.jar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Firebase service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > src/main/resources/firebase-service-account.json

      - name: Build with Gradle
        run: ./gradlew clean bootJar -x test -Pprofile=prod --no-daemon

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: build/libs/${{ env.JAR_NAME }}
          target: ${{ env.SERVICE_PATH }}
          strip_components: 2

      - name: Execute deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: SERVICE_PATH
          script: |
            export PROD_REDIS_HOST="${{ secrets.PROD_REDIS_HOST }}"
            export PROD_REDIS_PORT="${{ secrets.PROD_REDIS_PORT }}"
            export PROD_REDIS_PASSWORD="${{ secrets.PROD_REDIS_PASSWORD }}"
            export MAIL_HOST="${{ secrets.MAIL_HOST }}"
            export MAIL_PORT="${{ secrets.MAIL_PORT }}"
            export MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export PROD_RDB_HOST="${{ secrets.PROD_RDB_HOST }}"
            export PROD_RDB_USERNAME="${{ secrets.PROD_RDB_USERNAME }}"
            export PROD_RDB_PASSWORD="${{ secrets.PROD_RDB_PASSWORD }}"
            export PROD_JWT_SECRET="${{ secrets.PROD_JWT_SECRET }}"
            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            export PROD_AES_SECRET="${{ secrets.PROD_AES_SECRET }}"
            cd ${{ env.SERVICE_PATH }}
            chmod +x deploy.sh
            ./deploy.sh
